name: .NET Build

on:

  push:

    branches: [ "dev", "beta" ]

  pull_request:

    branches: [ "dev", "beta" ]

jobs:

  build:

    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v2

    - name: Setup MSBuild

      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet

      uses: NuGet/setup-nuget@v1.0.5

    - name: setup-msbuild

      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Packages

      run: nuget restore MCServerBuilder.sln

    - name: Build solution

      run: msbuild MCServerBuilder.sln -t:rebuild -property:Configuration=Release

